/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:760d24de-a9f3-44b5-8207-dee3a47ba0c2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ldnbiD3Mj",
    "aws_user_pools_web_client_id": "1295ff35fucfdcron8851jol7j",
    "oauth": {}
};


export default awsmobile;
